function createfigure(Y1)
%CREATEFIGURE1(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 26-Aug-2014 22:33:05

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',12);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(Y1,'LineWidth',1);

% Create xlabel
xlabel('Time (s)','FontSize',16);

% Create ylabel
ylabel('Speed (km/h)','FontSize',16);

